baseURL: https://diydeveloper.io
disablePathToLower: true
title: DIYDeveloper.io
theme: danny

indexes:
  tag: "tags"
  topic: "topics"

params :
  # Shown in the home page
  sitetitle: DIY Developer
  subtitle: "Power tools, software, 3d printing"
  brand: "DIYDev"
  disqus: "dannydotnet"
  # CSS name for highlight.js
  #highlightjs: "androidstudio"
  dateFormat: "02 Jan 2006"
  #publishDir: "docs"
  googleAnalytics: "UA-48772536-1"

menu:
 main:
    - name: "Home"
      pre: "<i class='fa fa-home fa-fw'></i>"
      weight: 1
      identifier: "home"
      url: "/"
    - name: "Archive"
      pre: "<i class='fa fa-list fa-fw'></i>"
      weight: 2
      identifier: "archive"
      url: "/archive/"
    - name: "About"
      pre: "<i class='fa fa-user fa-fw'></i>"
      weight: 3
      identifier: "about"
      url: "/about/"
social:
  github: "dfrencham"